### ISSUE TITLE
data is missing in the git repo

### ISSUE THREAD

**Issue by monajalal** [weigq/3d_pose_baseline_pytorch#24]
Could you please share the data/stat_3d.pth.tar ?

```
[jalal@goku 3d_pose_baseline_pytorch]$ python main.py --exp example

==================Options=================
{   'action': 'All',
    'ckpt': 'checkpoint/example',
    'data_dir': 'data/',
    'dropout': 0.5,
    'epochs': 200,
    'exp': 'example',
    'is_train': True,
    'job': 8,
    'linear_size': 1024,
    'load': '',
    'lr': 0.001,
    'lr_decay': 100000,
    'lr_gamma': 0.96,
    'max_norm': True,
    'num_stage': 2,
    'procrustes': False,
    'resume': False,
    'test': False,
    'test_batch': 64,
    'train_batch': 64,
    'use_hg': False}
==========================================

>>> creating model
/scratch3/3d_pose/humanpose/3d_pose_baseline_pytorch/src/model.py:11: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight)
>>> total params: 4.29M
/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
>>> actions to use (total: 15):
[   'Directions',
    'Discussion',
    'Eating',
    'Greeting',
    'Phoning',
    'Photo',
    'Posing',
    'Purchases',
    'Sitting',
    'SittingDown',
    'Smoking',
    'Waiting',
    'WalkDog',
    'Walking',
    'WalkTogether']
>>>
>>> loading data
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    main(option)
  File "main.py", line 75, in main
    stat_3d = torch.load(os.path.join(opt.data_dir, 'stat_3d.pth.tar'))
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/stat_3d.pth.tar'
```

**Comment by MCLYang** [comment]
Same issue

**Comment by qinchn** [comment]
+1

**Comment by bryanbocao** [comment]
+1

**Comment by zxp6329** [comment]
+1

**Comment by ShuangjunLiu** [comment]
+1

**Comment by alvarogonjim** [comment]
@monajalal  I uploaded al the data included the stats_3d in [Google Drive](https://drive.google.com/drive/folders/1kwBW5fxZqbUvv5UtkDy0NfWmWusT1Yg0?usp=sharing
)

**Comment by hodaebrahimi** [comment]
> @monajalal I uploaded al the data included the stats_3d in [Google Drive](https://drive.google.com/drive/folders/1kwBW5fxZqbUvv5UtkDy0NfWmWusT1Yg0?usp=sharing)

Hi, this link is not there anymore!
