### ISSUE TITLE
KeyError: "filename 'storages' not found"

### ISSUE THREAD

**Issue by abhikhanna30** [weigq/3d_pose_baseline_pytorch#6]
getting this error while loading data. Am i missing something?

**Comment by weigq** [comment]
@abhikhanna30 
is there any more info?

**Comment by abhikhanna30** [comment]
when i was doing torch.load(train_3d.pth.tar) for example on my gpu , i was getting the error:

_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhijeet/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/abhijeet/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 527, in _load
    return legacy_load(f)
  File "/home/abhijeet/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 441, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/abhijeet/anaconda3/lib/python3.6/tarfile.py", line 2039, in extract
    tarinfo = self.getmember(member)
  File "/home/abhijeet/anaconda3/lib/python3.6/tarfile.py", line 1750, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

**Comment by weigq** [comment]
This is due to python version, the codes only tested in pytho2.7, there are some problems in python3
