### ISSUE TITLE
'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by Ssrzbao** [weigq/3d_pose_baseline_pytorch#7]
I have download the pretrianed model gt_ckpt_best.pth.tar. But when I run the command python main.py --load gt_ckpt_best.pth.tar --test, the error 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128) has occurred.

**Comment by Ssrzbao** [comment]
What coding format is this trained model?

**Comment by weigq** [comment]
@Ssrzbao 
Did you use Pyhton2 ?
The data is saved using torch in python2.7, it will cause error when loading using Python3

**Comment by weigq** [comment]
@ahwaleed 
You`d best use 2.7,  I have tested on python3, where some errors occur.

**Comment by ahwaleed** [comment]
Thanks @weigq. Using python 2.7 worked!
However, now I am getting this error
`IOError: [Errno 2] No such file or directory: 'data/stat_3d.pth.tar'`

Where can I get this stat file?

**Comment by tobiascz** [comment]
```
import pickle
from functools import partial
...        
pickle.load = partial(pickle.load, encoding="latin1")
pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
ckpt = torch.load(opt.load, pickle_module=pickle)
```

worked for me

**Comment by NguyenDangBinh** [comment]
dear @tobiascz  ,

import pickle
from functools import partial
...        
pickle.load = partial(pickle.load, encoding="latin1")
pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
ckpt = torch.load(opt.load, pickle_module=pickle)


where did you add them?

**Comment by tobiascz** [comment]
> dear @tobiascz ,
> 
> import pickle
> from functools import partial
> ...
> pickle.load = partial(pickle.load, encoding="latin1")
> pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
> ckpt = torch.load(opt.load, pickle_module=pickle)
> 
> where did you add them?

the imports at the very start. And the stuff after ... exactly where you load your model ckpt in the original file. the two lines with pickle.load and pickle.Unpickler are basically used in ckpt=torch.load(opt.load, pickle_module=pickle) to change the encoding. Hope this helps

**Comment by NguyenDangBinh** [comment]
dear @tobiascz ,
I run by GPU.
I replaced it like picture below, but it still the same error.
![error](https://user-images.githubusercontent.com/30711163/51832324-4df75280-232f-11e9-8679-3734fb85d350.png)

**Comment by NguyenDangBinh** [comment]
I save the folder like that
![error](https://user-images.githubusercontent.com/30711163/51832427-99a9fc00-232f-11e9-8127-2e1885722a08.png)

**Comment by NguyenDangBinh** [comment]
error like

**Comment by NguyenDangBinh** [comment]
I think the pickle which is not run.
![error2](https://user-images.githubusercontent.com/30711163/51842818-b6a0f800-234c-11e9-93ba-3de327addeff.jpg)

**Comment by NguyenDangBinh** [comment]
![error3](https://user-images.githubusercontent.com/30711163/51843570-4004fa00-234e-11e9-9dfc-3546cbadde82.jpg)

**Comment by NguyenDangBinh** [comment]
dear @tobiascz,
May you help me?

**Comment by tobiascz** [comment]
@NguyenDangBinh It's hard for me to help you. The problem seems to be a very specific one. I would try to make a new conda environment with python 3.6 and install torch version 1 in there. I noticed that your environment is called 'tensorflow-gpu' and in this project you want to use pytorch. I had some issues when installing both pytorch and tensorflow side by side in one environment or globally. So I would try to create a new env with pytorch and without tensorflow.

**Comment by jjedele** [comment]
@tobiascz , @NguyenDangBinh :

1. It seems PyTorch's `load()` function also handles unpickling arguments directly (https://github.com/pytorch/pytorch/blob/6a6983ed7f14f8335a5b5614928713cb79658281/torch/serialization.py#L301), so you probably do not have to monkey patch the pickle module but just can call `torch.load(opt.load, encoding='latin1')`.
2. If this does not work, maybe try unpickling your file directly first, this makes debugging easier since you remove the indirection.

**Comment by jjedele** [comment]
Also, are you sure it's encoded in 'latin1'? When I google for the error, some answers hint at UTF8 (e.g. https://stackoverflow.com/questions/21393758/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe5-in-position-0-ordinal)

So maybe also give `encoding='utf-8'` a try.

**Comment by NguyenDangBinh** [comment]
> @NguyenDangBinh It's hard for me to help you. The problem seems to be a very specific one. I would try to make a new conda environment with python 3.6 and install torch version 1 in there. I noticed that your environment is called 'tensorflow-gpu' and in this project you want to use pytorch. I had some issues when installing both pytorch and tensorflow side by side in one environment or globally. So I would try to create a new env with pytorch and without tensorflow.

yes, it should be python 2.7

**Comment by YinRui1991** [comment]
I meet the same error. My pytorch version is  pytorch-1.0.1 (py3.6_cuda10.0.130_cudnn7.4.2_2) and python version is 3.6.8.
The following is the error:

`>>> loading data
Traceback (most recent call last):
  File "main.py", line 286, in <module>
    main(option)
  File "main.py", line 85, in main
    stat_3d = torch.load(os.path.join(opt.data_dir, 'stat_3d.pth.tar'))
  File "/home/pangziwei/anaconda3/envs/pytorch_cuda10/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/pangziwei/anaconda3/envs/pytorch_cuda10/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x91 in position 24: ordinal not in range(128)
`
I think it is caused by python3 encoding. So I open the source code of "serialization.py", and changes as below:

 _sys_info = pickle_module.load(f, encoding='iso-8859-1')
 unpickler = pickle_module.Unpickler(f, encoding='iso-8859-1')
 unpickler.persistent_load = persistent_load

And it works.

**Comment by danielajisafe** [comment]
> I have download the pretrianed model gt_ckpt_best.pth.tar. But when I run the command python main.py --load gt_ckpt_best.pth.tar --test, the error 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128) has occurred.

@Ssrzbao Can you please share the pre-trained model you downloaded? (gt_ckpt_best.pth.tar). The current url to the drive is broken.
